name: altinn_authorization
services:
  valkey:
    image: valkey/valkey:9.0-alpine3.24
    container_name: altinn_authorization_valkey
    ports:
      - "8002:6379"
    environment:
      VALKEY_PASSWORD: admin
    command: ["sh", "-c", "valkey-server --requirepass $$VALKEY_PASSWORD --appendonly yes"]
    healthcheck:
      test: ["CMD-SHELL", "REDISCLI_AUTH=$$VALKEY_PASSWORD valkey-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - valkey_data:/data
    networks:
      - auth
    restart: unless-stopped
  postgres:
    image: postgres
    container_name: altinn_authorization_postgres
    restart: always
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    networks:
      - auth
    volumes:
      - altinn_authorization_data:/postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: altinn_authorization_pgadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - auth
    volumes:
      - altinn_authorization_data:/pgadmin

networks:
  auth:
    driver: bridge

volumes:
  altinn_authorization_data:
  valkey_data:
    driver: local

