apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: accessmanagement-apps
  namespace: product-accessmanagement
spec:
  interval: 10m
  path: ./environments/at22
  prune: true
  sourceRef:
    kind: OCIRepository
    name: accessmanagement-manifests
  targetNamespace: product-accessmanagement
