apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: access-management-apps
  namespace: product-access-management
spec:
  interval: 10m
  path: ./environments/at22
  prune: true
  sourceRef:
    kind: OCIRepository
    name: access-management-manifests
  targetNamespace: product-access-management
