apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: accessmanagement-manifests
  namespace: product-accessmanagement
spec:
  interval: 10m
  provider: azure
  url: oci://altinncr.azurecr.io/accessmanagement/altinn-auth
  ref:
    tag: main
