apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-authorization
labels:
  - pairs:
      app.kubernetes.io/component: access-management
      app.kubernetes.io/part-of: authorization
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: false

resources:
  - auto-scaler.yaml
  - config-map-runtime.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
