apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: authorization-runtime
  labels:
    app.kubernetes.io/name: authorization
    app.kubernetes.io/part-of: authorization
spec: {}
