apiVersion: v1
kind: Service
metadata:
  name: access-management
  labels:
    app.kubernetes.io/name: access-management
    app.kubernetes.io/part-of: accessmanagement
spec:
  selector:
    app.kubernetes.io/name: access-management
    app.kubernetes.io/part-of: accessmanagement
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
