apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/name: authorization
    app.kubernetes.io/part-of: authorization
    azure.workload.identity/use: "true"
  includeSelectors: true
  includeTemplates: true

resources:
  - 02-deployment.yaml
  - 03-service.yaml
  - 04-route.yaml
