apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: pre-deploy
  labels:
    app.kubernetes.io/name: access-management-pre-deploy
    app.kubernetes.io/part-of: accessmanagement
spec: {}

