apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-database
  labels:
    app.kubernetes.io/name: access-management-migrate-database
    app.kubernetes.io/part-of: accessmanagement
spec:
  activeDeadlineSeconds: 86400 # 24 hours
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: access-management-migrate-database
        app.kubernetes.io/part-of: accessmanagement
    spec:
      serviceAccountName: access-management-pre-deploy

      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        allowPrivilegeEscalation: false

      containers:
        - name: accessmanagement
          image: ghcr.io/altinn/altinn-auth/accessmanagement:{{GIT_SHA}}
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: environment
          env:
            - name: RunInitOnly
              value: 'true'
