name: "Apps / CD"

on:
  push:
    branches:
      - fix/dis
    
permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        name: Checkout repository

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

