name: "Publish Syncroot"
run-name: ${{ inputs.app }} ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      vertical_id:
        description: App
        type: choice
        required: true
        options:
          - app:Altinn.AccessManagement
          - app:Altinn.Authorization

      environment:
        description: "Environment"
        type: choice
        required: true
        options:
          - at22
          - at23
          - at24
          - tt02
          - yt01
          - prod

permissions:
  contents: read
  id-token: write

concurrency:
  group: publish-flux-artifacts-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  publish-app-syncroot:
    name: Publish Syncroot Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: Altinn/altinn-auth/.github/actions/init@8785549c5be10aeef8ec31c6c7010d593a8c9128

      - name: Extract app config
        run: |
          repoctl github export-vertical ${{ inputs.vertical_id}}

      - name: Build and push syncroot artifact
        uses: Altinn/altinn-platform/actions/flux/build-push-image@3535bba3d301df5778ce420f7adf10edd748cc3f # main
        with:
          image_name: ${{ env.VERTICAL_DIR }}/syncroot
          tag: ${{ inputs.environment }}
          workdir: ./src/apps/${{ env.VERTICAL_NAME }}/syncroot
          azure_subscription_id: ${{ secrets.DIS_SYNCROOT_AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.DIS_SYNCROOT_AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.DIS_SYNCROOT_AZURE_TENANT_ID }}
